# Generated by Django 4.0.1 on 2022-02-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='images',
        ),
    ]
